Watching for file changes with StatReloader
C:\Users\DEV-018\Desktop\sakib\demo\demo\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\DEV-018\Desktop\sakib\demo\demo\settings.py changed, reloading.
INFO Watching for file changes with StatReloader
DEBUG Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
INFO Get request for a particular data 
DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
WARNING Error in Get request in Snippet details .....GET Snippet matching query does not exist.
ERROR Internal Server Error: /sd/19/
Traceback (most recent call last):
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 39, in sentry_patched_render
    return old_render(self)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DoesNotExist is not JSON serializable
DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
INFO C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
INFO Watching for file changes with StatReloader
INFO C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
INFO Watching for file changes with StatReloader
DEBUG Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
WARNING Error in Get request in Snippet details .....GET 
ERROR Internal Server Error: /sd/19/
Traceback (most recent call last):
  File "C:\Users\DEV-018\Desktop\sakib\demo\base\views.py", line 49, in get
    s1=Snippet.objects.get(pk=pk)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
base.models.Snippet.DoesNotExist: Snippet matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\Desktop\sakib\demo\base\views.py", line 54, in get
    return Response({"error":err})
                             ^^^
NameError: name 'err' is not defined
DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
INFO C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
INFO Watching for file changes with StatReloader
INFO C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
INFO Watching for file changes with StatReloader
DEBUG Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
WARNING Error in Get request in Snippet details .....GET 
ERROR Internal Server Error: /sd/19/
Traceback (most recent call last):
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\Desktop\sakib\demo\base\views.py", line 55, in get
    ser1=SnippetSerlizers(s1)
                          ^^
UnboundLocalError: cannot access local variable 's1' where it is not associated with a value
DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
INFO C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
INFO Watching for file changes with StatReloader
INFO C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
INFO Watching for file changes with StatReloader
DEBUG Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
WARNING Error in Get request in Snippet details .....GET 
INFO Get request for a particular data 
ERROR Internal Server Error: /sd/19/
Traceback (most recent call last):
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\Desktop\sakib\demo\base\views.py", line 58, in get
    return Response({"Response":ser1.data})
                                ^^^^
UnboundLocalError: cannot access local variable 'ser1' where it is not associated with a value
DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
INFO C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
INFO Watching for file changes with StatReloader
INFO C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
INFO Watching for file changes with StatReloader
DEBUG Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
INFO C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
INFO Watching for file changes with StatReloader
DEBUG Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
WARNING Error in Get request in Snippet details .....GET 
ERROR Internal Server Error: /sd/19/
Traceback (most recent call last):
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Expected a `Response`, `HttpResponse` or `StreamingHttpResponse` to be returned from the view, but received a `<class 'NoneType'>`
DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
INFO C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
INFO Watching for file changes with StatReloader
INFO C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
INFO Watching for file changes with StatReloader
DEBUG Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
WARNING Error in Get request in Snippet details .....GET 
DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
INFO C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
DEBUG Resetting dropped connection: o4507225874235392.ingest.us.sentry.io
DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
INFO Watching for file changes with StatReloader
INFO C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
INFO Watching for file changes with StatReloader
DEBUG Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
WARNING Error in Get request in Snippet details .....GET Snippet matching query does not exist.
ERROR Internal Server Error: /sd/19/
Traceback (most recent call last):
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 39, in sentry_patched_render
    return old_render(self)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DoesNotExist is not JSON serializable
DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
INFO Get request for a particular data 
DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
INFO C:\Users\DEV-018\Desktop\sakib\demo\demo\settings.py changed, reloading.
DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
2024-05-09 18:04:39,682INFO Watching for file changes with StatReloader
2024-05-09 18:04:43,299INFO C:\Users\DEV-018\Desktop\sakib\demo\demo\settings.py changed, reloading.
2024-05-09 18:04:44,583 INFO Watching for file changes with StatReloader
2024-05-09 18:04:48,108 DEBUG Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
2024-05-09 18:04:48,115 INFO Get request for a particular data 
2024-05-09 18:04:48,602 DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
2024-05-09 18:04:48,746 DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
2024-05-09 18:06:25,019 INFO C:\Users\DEV-018\Desktop\sakib\demo\demo\settings.py changed, reloading.
2024-05-09 18:06:25,186 DEBUG https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
2024-05-09 18:06:26,212 INFO Watching for file changes with StatReloader
2024-05-09 18:06:31,970 INFO C:\Users\DEV-018\Desktop\sakib\demo\demo\settings.py changed, reloading.
django.utils.autoreload INFO 2024-05-09 18:08:20,539 autoreload 17868 4120 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-09 18:08:42,370 connectionpool 17868 19092 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
base.views INFO 2024-05-09 18:08:42,386 views 17868 5964 Get request for a particular data 
urllib3.connectionpool DEBUG 2024-05-09 18:08:42,864 connectionpool 17868 19092 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-09 18:08:43,027 connectionpool 17868 19092 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
base.views WARNING 2024-05-09 18:09:55,152 views 17868 5644 Error in Get request in Snippet details .....GET Snippet matching query does not exist.
django.request ERROR 2024-05-09 18:09:55,199 log 17868 5644 Internal Server Error: /sd/19/
Traceback (most recent call last):
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 39, in sentry_patched_render
    return old_render(self)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DoesNotExist is not JSON serializable
urllib3.connectionpool DEBUG 2024-05-09 18:09:55,596 connectionpool 17868 19092 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-09 18:09:55,775 connectionpool 17868 19092 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-09 18:09:55,936 connectionpool 17868 19092 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
base.views INFO 2024-05-09 18:10:22,881 views 17868 17444 Get request for a particular data 
urllib3.connectionpool DEBUG 2024-05-09 18:10:23,030 connectionpool 17868 19092 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-09 18:10:23,198 connectionpool 17868 19092 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-09 18:23:26,637 connectionpool 17868 19092 Resetting dropped connection: o4507225874235392.ingest.us.sentry.io
urllib3.connectionpool DEBUG 2024-05-09 18:23:27,228 connectionpool 17868 19092 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-10 12:28:25,212 autoreload 15148 13976 Watching for file changes with StatReloader
base.views INFO 2024-05-10 12:32:40,254 views 15148 14576 Get request for a particular data 
urllib3.connectionpool DEBUG 2024-05-10 12:32:40,459 connectionpool 15148 15356 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
django.request WARNING 2024-05-10 12:32:40,942 log 15148 284 Not Found: /favicon.ico
urllib3.connectionpool DEBUG 2024-05-10 12:32:41,221 connectionpool 15148 15356 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-10 12:32:41,431 connectionpool 15148 15356 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-10 12:32:41,635 connectionpool 15148 15356 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-10 12:32:41,840 connectionpool 15148 15356 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-10 12:32:42,043 connectionpool 15148 15356 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-10 12:32:42,243 connectionpool 15148 15356 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-10 12:32:42,451 connectionpool 15148 15356 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-10 12:32:42,658 connectionpool 15148 15356 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-10 12:32:42,864 connectionpool 15148 15356 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-10 12:32:43,066 connectionpool 15148 15356 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-10 12:32:43,273 connectionpool 15148 15356 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-10 12:32:43,478 connectionpool 15148 15356 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-10 12:32:43,676 connectionpool 15148 15356 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-10 12:32:43,888 connectionpool 15148 15356 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
base.views WARNING 2024-05-10 12:32:52,786 views 15148 16296 Error in Get request in Snippet details .....GET Snippet matching query does not exist.
django.request ERROR 2024-05-10 12:32:52,958 log 15148 16296 Internal Server Error: /sd/18/
Traceback (most recent call last):
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 39, in sentry_patched_render
    return old_render(self)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\renderers.py", line 726, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\renderers.py", line 682, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\renderers.py", line 412, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DoesNotExist is not JSON serializable
urllib3.connectionpool DEBUG 2024-05-10 12:32:53,293 connectionpool 15148 15356 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-10 12:32:53,514 connectionpool 15148 15356 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-10 12:32:53,717 connectionpool 15148 15356 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-10 13:01:15,150 autoreload 15148 13976 C:\Users\DEV-018\Desktop\sakib\demo\demo\settings.py changed, reloading.
urllib3.connectionpool DEBUG 2024-05-10 13:01:15,158 connectionpool 15148 15356 Resetting dropped connection: o4507225874235392.ingest.us.sentry.io
urllib3.connectionpool DEBUG 2024-05-10 13:01:15,718 connectionpool 15148 15356 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-10 13:01:16,780 autoreload 15784 13836 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-10 13:01:23,558 autoreload 15784 13836 C:\Users\DEV-018\Desktop\sakib\demo\demo\urls.py changed, reloading.
django.utils.autoreload INFO 2024-05-10 13:01:24,541 autoreload 7872 6704 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-10 13:06:42,360 autoreload 7872 6704 C:\Users\DEV-018\Desktop\sakib\demo\demo\settings.py changed, reloading.
django.utils.autoreload INFO 2024-05-10 13:06:43,231 autoreload 14980 6632 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-10 13:11:12,375 autoreload 14980 6632 C:\Users\DEV-018\Desktop\sakib\demo\demo\wsgi.py changed, reloading.
django.utils.autoreload INFO 2024-05-10 13:11:13,190 autoreload 7388 15728 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-10 13:11:52,440 autoreload 7388 15728 C:\Users\DEV-018\Desktop\sakib\demo\demo\settings.py changed, reloading.
django.utils.autoreload INFO 2024-05-10 13:11:53,639 autoreload 6600 15004 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-10 13:11:53,946 connectionpool 6600 5056 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-10 13:11:54,501 connectionpool 6600 5056 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-10 13:14:03,101 autoreload 6600 15004 C:\Users\DEV-018\Desktop\sakib\demo\demo\settings.py changed, reloading.
django.utils.autoreload INFO 2024-05-10 13:14:03,950 autoreload 14144 15664 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-10 13:50:42,372 autoreload 17232 16976 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-10 13:51:36,264 autoreload 18408 8476 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-10 13:56:43,202 autoreload 18408 8476 C:\Users\DEV-018\Desktop\sakib\demo\demo\settings.py changed, reloading.
django.utils.autoreload INFO 2024-05-10 13:56:43,869 autoreload 16624 17816 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-10 13:56:51,932 autoreload 16624 17816 C:\Users\DEV-018\Desktop\sakib\demo\demo\settings.py changed, reloading.
django.utils.autoreload INFO 2024-05-10 13:56:52,796 autoreload 17604 17732 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-10 13:56:58,717 autoreload 17604 17732 C:\Users\DEV-018\Desktop\sakib\demo\demo\settings.py changed, reloading.
django.utils.autoreload INFO 2024-05-10 13:56:59,588 autoreload 17752 17436 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-10 13:57:28,676 autoreload 16600 9468 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-10 13:58:39,493 autoreload 17172 17320 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-10 14:00:34,327 autoreload 6488 14436 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-10 14:00:56,018 autoreload 18160 9644 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-10 14:02:53,107 autoreload 16160 1800 Watching for file changes with StatReloader
base.views INFO 2024-05-10 14:03:07,795 views 16160 7040 Get request for a particular data 
django.utils.autoreload INFO 2024-05-13 10:57:42,742 autoreload 3508 11432 Watching for file changes with StatReloader
base.views INFO 2024-05-13 10:57:52,730 views 3508 14216 Get request for a particular data 
django.request WARNING 2024-05-13 10:58:01,057 log 3508 14216 Not Found: /sd/1_
django.utils.autoreload INFO 2024-05-13 11:02:00,352 autoreload 3508 11432 C:\Users\DEV-018\Desktop\sakib\demo\demo\urls.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:02:02,195 autoreload 16368 18924 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:02:15,670 autoreload 16368 18924 C:\Users\DEV-018\Desktop\sakib\demo\demo\urls.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:02:17,465 autoreload 3472 18732 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:02:21,405 autoreload 3472 18732 C:\Users\DEV-018\Desktop\sakib\demo\demo\urls.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:02:23,140 autoreload 17716 11164 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 11:02:32,916 connectionpool 17716 6352 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
django.request ERROR 2024-05-13 11:02:32,981 log 17716 9992 Internal Server Error: /sentry-debug/
Traceback (most recent call last):
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\Desktop\sakib\demo\demo\urls.py", line 23, in trigger_error
    division_by_zero = 1 / 0
                       ~~^~~
ZeroDivisionError: division by zero
django.request WARNING 2024-05-13 11:02:33,161 log 17716 9992 Not Found: /favicon.ico
urllib3.connectionpool DEBUG 2024-05-13 11:02:33,622 connectionpool 17716 6352 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
base.views WARNING 2024-05-13 11:03:13,765 views 17716 6428 Error in Get request in Snippet details .....GET Snippet matching query does not exist.
django.request ERROR 2024-05-13 11:03:13,862 log 17716 6428 Internal Server Error: /sd/18/
Traceback (most recent call last):
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 39, in sentry_patched_render
    return old_render(self)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DoesNotExist is not JSON serializable
urllib3.connectionpool DEBUG 2024-05-13 11:03:13,930 connectionpool 17716 6352 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-13 11:03:14,096 connectionpool 17716 6352 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 11:06:12,046 autoreload 17716 11164 C:\Users\DEV-018\Desktop\sakib\demo\demo\settings.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:06:13,831 autoreload 15388 1312 Watching for file changes with StatReloader
base.views WARNING 2024-05-13 11:06:29,682 views 15388 3872 Error in Get request in Snippet details .....GET Snippet matching query does not exist.
urllib3.connectionpool DEBUG 2024-05-13 11:06:29,683 connectionpool 15388 11936 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
django.request ERROR 2024-05-13 11:06:29,736 log 15388 3872 Internal Server Error: /sd/18/
Traceback (most recent call last):
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 39, in sentry_patched_render
    return old_render(self)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DoesNotExist is not JSON serializable
urllib3.connectionpool DEBUG 2024-05-13 11:06:30,274 connectionpool 15388 11936 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-13 11:06:30,457 connectionpool 15388 11936 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 11:12:09,946 autoreload 15388 1312 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:12:11,936 autoreload 7824 12348 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:12:52,344 autoreload 7824 12348 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:12:54,241 autoreload 8664 4856 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:12:55,900 autoreload 8664 4856 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:12:57,739 autoreload 13476 8700 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:13:00,577 autoreload 13476 8700 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:13:02,486 autoreload 1792 2904 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:14:13,659 autoreload 1792 2904 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:14:15,671 autoreload 17636 2200 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:16:02,982 autoreload 17636 2200 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:16:04,678 autoreload 18708 4652 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:16:43,292 autoreload 18708 4652 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:16:44,998 autoreload 15528 18140 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:16:49,033 autoreload 15528 18140 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:16:50,740 autoreload 12196 17168 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:21:16,839 autoreload 13572 3732 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:22:27,895 autoreload 12196 17168 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:22:28,776 autoreload 13572 3732 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:22:30,073 autoreload 12836 6364 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:22:31,018 autoreload 9344 9252 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:23:44,991 autoreload 9344 9252 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:23:45,197 autoreload 12836 6364 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:23:46,786 autoreload 12512 10324 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:23:47,043 autoreload 18588 4076 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:24:30,170 autoreload 12512 10324 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:24:30,194 autoreload 18588 4076 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:24:32,347 autoreload 1972 10112 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:24:32,352 autoreload 14896 12772 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:24:37,767 autoreload 1972 10112 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:24:37,774 autoreload 14896 12772 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:24:39,764 autoreload 17096 11092 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:24:39,768 autoreload 3048 3148 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 11:24:40,011 connectionpool 17096 15056 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 11:24:40,014 connectionpool 3048 14128 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 11:24:41,148 connectionpool 3048 14128 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-13 11:24:41,148 connectionpool 17096 15056 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 11:24:41,970 autoreload 3048 3148 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:24:41,992 autoreload 17096 11092 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:24:43,979 autoreload 5284 15968 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:24:43,997 autoreload 15936 16908 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 11:24:44,158 connectionpool 5284 12808 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 11:24:44,227 connectionpool 15936 14928 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 11:24:44,938 connectionpool 5284 12808 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-13 11:24:44,947 connectionpool 15936 14928 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 11:24:46,981 autoreload 15936 16908 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:24:47,006 autoreload 5284 15968 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:24:49,034 autoreload 13132 17468 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:24:49,040 autoreload 15104 8240 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 11:24:49,208 connectionpool 15104 15500 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 11:24:49,216 connectionpool 13132 568 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 11:24:50,065 connectionpool 13132 568 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-13 11:24:50,083 connectionpool 15104 15500 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 11:24:53,155 autoreload 15104 8240 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:24:53,190 autoreload 13132 17468 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:24:55,218 autoreload 11848 2460 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:24:55,255 autoreload 11784 1268 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 11:24:55,518 connectionpool 11848 1528 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 11:24:55,527 connectionpool 11784 5564 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 11:24:56,403 connectionpool 11848 1528 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-13 11:24:56,435 connectionpool 11784 5564 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 11:25:01,613 autoreload 11784 1268 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:25:01,623 autoreload 11848 2460 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:25:03,657 autoreload 6352 5108 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:25:03,662 autoreload 18336 12152 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 11:25:03,944 connectionpool 18336 18508 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 11:25:03,956 connectionpool 6352 11180 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 11:25:04,804 connectionpool 18336 18508 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 11:25:06,771 autoreload 18336 12152 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:25:06,777 autoreload 6352 5108 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:25:08,690 autoreload 14120 10320 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:25:08,693 autoreload 9920 9168 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 11:25:08,885 connectionpool 9920 15788 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 11:25:08,890 connectionpool 14120 17816 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 11:25:09,719 connectionpool 14120 17816 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 11:25:12,771 autoreload 14120 10320 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:25:12,787 autoreload 9920 9168 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:25:14,752 autoreload 6128 17420 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:25:14,760 autoreload 13576 11912 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:25:20,096 autoreload 6128 17420 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:25:20,100 autoreload 13576 11912 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:25:22,073 autoreload 14064 3380 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:25:22,074 autoreload 14964 5988 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:25:24,011 autoreload 14964 5988 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:25:24,037 autoreload 14064 3380 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:25:25,818 autoreload 11204 4908 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:25:25,830 autoreload 5992 10364 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:26:09,211 autoreload 5992 10364 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:26:09,687 autoreload 11204 4908 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:26:11,128 autoreload 9476 3220 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:26:11,655 autoreload 16256 2652 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:26:20,352 autoreload 9476 3220 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:26:20,947 autoreload 16256 2652 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:26:22,472 autoreload 12852 8792 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:26:23,180 autoreload 9312 17812 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:26:50,382 autoreload 9312 17812 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:26:50,929 autoreload 12852 8792 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:26:52,170 autoreload 3052 13464 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:26:52,792 autoreload 18828 11380 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:27:16,584 autoreload 3052 13464 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:27:16,828 autoreload 18828 11380 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:27:18,567 autoreload 7052 12576 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:27:18,898 autoreload 2188 13616 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:27:48,321 autoreload 2188 13616 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:27:48,673 autoreload 7052 12576 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:27:50,360 autoreload 14584 15136 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:27:50,766 autoreload 10868 15044 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:28:07,080 autoreload 14584 15136 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:28:07,325 autoreload 10868 15044 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:28:08,967 autoreload 520 4132 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:28:09,253 autoreload 4688 2768 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:28:13,010 autoreload 520 4132 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:28:13,222 autoreload 4688 2768 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:28:15,163 autoreload 1796 2884 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:28:15,412 autoreload 2308 8620 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:28:17,096 autoreload 1796 2884 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:28:18,768 autoreload 3304 13136 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:28:29,163 autoreload 3304 13136 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:28:29,169 autoreload 2308 8620 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:28:31,138 autoreload 4548 11624 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:28:31,137 autoreload 7924 18076 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 11:28:31,405 connectionpool 7924 18636 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 11:28:31,407 connectionpool 4548 16128 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 11:28:32,128 connectionpool 4548 16128 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-13 11:28:32,128 connectionpool 7924 18636 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 11:28:34,149 autoreload 7924 18076 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:28:34,152 autoreload 4548 11624 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:28:36,202 autoreload 16804 7308 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:28:36,210 autoreload 15532 16716 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 11:28:36,735 connectionpool 16804 1376 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 11:28:36,742 connectionpool 15532 7176 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 11:28:37,562 connectionpool 15532 7176 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-13 11:28:37,573 connectionpool 16804 1376 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 11:28:54,608 autoreload 15532 16716 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:28:54,630 autoreload 16804 7308 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:28:56,744 autoreload 15824 16136 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:28:56,754 autoreload 17544 15472 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 11:28:57,052 connectionpool 15824 18764 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 11:28:57,068 connectionpool 17544 14216 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 11:28:57,972 connectionpool 17544 14216 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 11:29:19,141 autoreload 15824 16136 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:29:19,169 autoreload 17544 15472 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:29:21,259 autoreload 3148 3048 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:29:21,271 autoreload 11644 4056 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:29:35,067 autoreload 3148 3048 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:29:36,107 autoreload 11644 4056 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:29:37,325 autoreload 14080 6428 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:29:38,421 autoreload 17468 13132 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:29:44,462 autoreload 17468 13132 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:29:44,516 autoreload 14080 6428 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:29:46,671 autoreload 19372 18708 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:29:46,729 autoreload 11848 4296 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:29:51,930 autoreload 19372 18708 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:29:51,975 autoreload 11848 4296 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:29:53,896 autoreload 17816 15788 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:29:53,907 autoreload 9396 7908 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:30:00,253 autoreload 17816 15788 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:30:00,300 autoreload 9396 7908 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:30:02,330 autoreload 6676 14052 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:30:02,390 autoreload 4632 14972 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:30:04,407 autoreload 6676 14052 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:30:04,440 autoreload 4632 14972 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:30:06,221 autoreload 11616 5988 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:30:06,266 autoreload 14480 17768 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:30:18,892 autoreload 11616 5988 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:30:18,936 autoreload 14480 17768 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:30:21,106 autoreload 3392 1524 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:30:21,135 autoreload 12376 17204 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:31:13,171 autoreload 12376 17204 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:31:13,620 autoreload 3392 1524 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:31:15,169 autoreload 15528 6168 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:31:15,769 autoreload 4864 7500 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:31:51,927 autoreload 15528 6168 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:31:51,936 autoreload 4864 7500 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:31:54,423 autoreload 13504 4248 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:31:54,423 autoreload 5056 5884 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:32:32,951 autoreload 5056 5884 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:32:33,729 autoreload 13504 4248 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:32:35,184 autoreload 11152 5644 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 11:32:35,797 connectionpool 11152 12448 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
django.request ERROR 2024-05-13 11:32:35,858 log 11152 5700 Internal Server Error: /s/
Traceback (most recent call last):
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\Desktop\sakib\demo\base\views.py", line 37, in post
    if serlizers_data.is_valid():
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 442, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 495, in to_internal_value
    for field in fields:
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 378, in _writable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `user_Data` is not valid for model `Snippet` in `base.serlizers.snippetser`.
django.utils.autoreload INFO 2024-05-13 11:32:36,166 autoreload 18752 11556 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 11:32:36,700 connectionpool 11152 12448 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.request ERROR 2024-05-13 11:32:38,255 log 11152 5700 Internal Server Error: /s/
Traceback (most recent call last):
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\Desktop\sakib\demo\base\views.py", line 37, in post
    if serlizers_data.is_valid():
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 442, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 495, in to_internal_value
    for field in fields:
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 378, in _writable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `user_Data` is not valid for model `Snippet` in `base.serlizers.snippetser`.
urllib3.connectionpool DEBUG 2024-05-13 11:32:38,727 connectionpool 11152 12448 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 11:32:48,108 autoreload 11152 5644 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:32:48,933 autoreload 18752 11556 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:32:50,028 autoreload 3024 4480 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:32:50,957 autoreload 15312 16460 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:34:26,225 autoreload 15312 16460 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:34:27,020 autoreload 3024 4480 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:34:28,575 autoreload 19236 1344 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:34:29,237 autoreload 13304 4396 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:34:30,397 autoreload 19236 1344 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:34:31,030 autoreload 13304 4396 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:34:32,228 autoreload 12512 14988 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:34:32,838 autoreload 15464 13472 Watching for file changes with StatReloader
base.views WARNING 2024-05-13 11:36:34,206 views 12512 13752 Error in Get request in Snippet details .....GET Snippet matching query does not exist.
urllib3.connectionpool DEBUG 2024-05-13 11:36:34,207 connectionpool 12512 3264 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
django.request ERROR 2024-05-13 11:36:34,239 log 12512 13752 Internal Server Error: /sd/8/
Traceback (most recent call last):
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 39, in sentry_patched_render
    return old_render(self)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DoesNotExist is not JSON serializable
urllib3.connectionpool DEBUG 2024-05-13 11:36:34,929 connectionpool 12512 3264 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-13 11:36:35,089 connectionpool 12512 3264 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
base.views WARNING 2024-05-13 11:36:47,522 views 12512 13752 Error in Get request in Snippet details .....GET Snippet matching query does not exist.
django.request ERROR 2024-05-13 11:36:47,559 log 12512 13752 Internal Server Error: /sd/8/
Traceback (most recent call last):
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 39, in sentry_patched_render
    return old_render(self)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DoesNotExist is not JSON serializable
urllib3.connectionpool DEBUG 2024-05-13 11:36:47,687 connectionpool 12512 3264 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-13 11:36:47,857 connectionpool 12512 3264 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
base.views INFO 2024-05-13 11:36:56,597 views 12512 13752 Get request for a particular data 
django.request ERROR 2024-05-13 11:38:22,197 log 12512 13752 Internal Server Error: /sd/9/
Traceback (most recent call last):
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Expected a `Response`, `HttpResponse` or `StreamingHttpResponse` to be returned from the view, but received a `<class 'NoneType'>`
urllib3.connectionpool DEBUG 2024-05-13 11:38:22,712 connectionpool 12512 3264 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.request ERROR 2024-05-13 11:38:31,746 log 12512 13752 Internal Server Error: /sd/9/
Traceback (most recent call last):
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Expected a `Response`, `HttpResponse` or `StreamingHttpResponse` to be returned from the view, but received a `<class 'NoneType'>`
urllib3.connectionpool DEBUG 2024-05-13 11:38:32,205 connectionpool 12512 3264 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.request ERROR 2024-05-13 11:39:21,950 log 12512 13752 Internal Server Error: /sd/9/
Traceback (most recent call last):
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Expected a `Response`, `HttpResponse` or `StreamingHttpResponse` to be returned from the view, but received a `<class 'NoneType'>`
urllib3.connectionpool DEBUG 2024-05-13 11:39:22,100 connectionpool 12512 3264 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 11:39:39,932 autoreload 10628 1256 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 11:39:42,349 connectionpool 10628 568 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
django.request ERROR 2024-05-13 11:39:42,374 log 10628 13860 Internal Server Error: /sd/9/
Traceback (most recent call last):
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Expected a `Response`, `HttpResponse` or `StreamingHttpResponse` to be returned from the view, but received a `<class 'NoneType'>`
urllib3.connectionpool DEBUG 2024-05-13 11:39:42,993 connectionpool 10628 568 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 11:40:22,207 autoreload 10628 1256 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:40:23,858 autoreload 10816 13136 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:40:39,362 autoreload 10816 13136 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:40:41,529 autoreload 2700 12824 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:56:29,433 autoreload 2700 12824 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:56:31,270 autoreload 4220 10856 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 11:57:16,957 autoreload 4220 10856 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 11:57:18,616 autoreload 10628 3528 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 12:10:59,106 autoreload 10628 3528 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:11:01,023 autoreload 7664 8488 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 12:11:01,151 connectionpool 7664 16080 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 12:11:01,840 connectionpool 7664 16080 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 12:11:04,802 autoreload 7664 8488 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:11:06,843 autoreload 5956 14792 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 12:11:06,947 connectionpool 5956 17732 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 12:11:07,580 connectionpool 5956 17732 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 12:11:09,487 autoreload 5956 14792 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:11:11,237 autoreload 4360 5428 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 12:11:13,193 autoreload 4360 5428 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:11:14,912 autoreload 11988 19440 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 12:11:32,665 autoreload 11988 19440 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:11:34,639 autoreload 15148 14552 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 12:11:34,817 connectionpool 15148 3804 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 12:11:35,438 connectionpool 15148 3804 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 12:11:38,388 autoreload 15148 14552 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:11:40,151 autoreload 15184 16016 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 12:11:40,265 connectionpool 15184 4624 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 12:11:40,865 connectionpool 15184 4624 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 12:11:48,098 autoreload 15184 16016 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:11:50,081 autoreload 16092 15812 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 12:11:50,209 connectionpool 16092 11116 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 12:11:50,795 connectionpool 16092 11116 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 12:11:54,833 autoreload 16092 15812 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:11:56,672 autoreload 6428 6908 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 12:11:56,776 connectionpool 6428 15136 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 12:11:57,303 connectionpool 6428 15136 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 12:12:04,638 autoreload 6428 6908 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:12:06,463 autoreload 8052 17572 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 12:12:08,126 autoreload 8052 17572 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:12:09,895 autoreload 6864 2372 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 12:12:13,751 autoreload 6864 2372 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:12:15,597 autoreload 7668 11584 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 12:14:19,331 autoreload 7668 11584 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:14:20,936 autoreload 14452 17636 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 12:14:23,654 autoreload 14452 17636 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:14:25,398 autoreload 17016 13884 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 12:14:25,526 connectionpool 17016 11364 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 12:14:26,237 connectionpool 17016 11364 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 12:14:42,964 autoreload 17016 13884 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:14:44,776 autoreload 16344 3328 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 12:14:44,888 connectionpool 16344 16124 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 12:14:45,486 connectionpool 16344 16124 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 12:14:59,080 autoreload 16344 3328 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:15:00,882 autoreload 8404 3908 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 12:15:01,002 connectionpool 8404 18988 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 12:15:01,568 connectionpool 8404 18988 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 12:15:08,780 autoreload 8404 3908 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:15:10,660 autoreload 16716 17920 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 12:15:10,775 connectionpool 16716 16688 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 12:15:11,392 connectionpool 16716 16688 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 12:15:12,276 autoreload 16716 17920 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:15:13,955 autoreload 12856 4512 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 12:15:14,068 connectionpool 12856 17204 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 12:15:14,675 connectionpool 12856 17204 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 12:15:15,521 autoreload 12856 4512 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:15:17,341 autoreload 11280 3176 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 12:15:17,456 connectionpool 11280 15792 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 12:15:17,985 connectionpool 11280 15792 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 12:15:18,881 autoreload 11280 3176 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:15:20,580 autoreload 2796 2312 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 12:15:20,693 connectionpool 2796 16444 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 12:15:21,294 connectionpool 2796 16444 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 12:15:22,132 autoreload 2796 2312 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:15:23,910 autoreload 11756 9612 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 12:15:24,023 connectionpool 11756 19332 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 12:15:24,568 connectionpool 11756 19332 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 12:15:27,608 autoreload 11756 9612 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:15:29,287 autoreload 16352 10408 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 12:15:29,405 connectionpool 16352 14896 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 12:15:29,928 connectionpool 16352 14896 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 12:15:36,148 autoreload 16352 10408 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:15:37,846 autoreload 13016 15968 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 12:15:37,976 connectionpool 13016 7940 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 12:15:38,601 connectionpool 13016 7940 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 12:15:43,757 autoreload 13016 15968 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:15:45,553 autoreload 3884 6588 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 12:15:47,268 autoreload 3884 6588 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:15:49,025 autoreload 17420 16724 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 12:15:52,936 autoreload 17420 16724 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:15:54,737 autoreload 852 17048 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 12:15:57,647 autoreload 852 17048 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:15:59,502 autoreload 18548 5776 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 12:15:59,722 connectionpool 18548 17312 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 12:16:00,447 connectionpool 18548 17312 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 12:16:06,552 autoreload 18548 5776 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:16:08,259 autoreload 3936 16988 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 12:16:09,940 connectionpool 3936 13616 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
django.request ERROR 2024-05-13 12:16:09,980 log 3936 9292 Internal Server Error: /s/
Traceback (most recent call last):
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 39, in sentry_patched_render
    return old_render(self)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DoesNotExist is not JSON serializable
urllib3.connectionpool DEBUG 2024-05-13 12:16:10,669 connectionpool 3936 13616 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 12:16:46,708 autoreload 3936 16988 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:16:48,624 autoreload 18272 1796 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 12:16:50,307 autoreload 18272 1796 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:16:51,948 autoreload 3680 15972 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 12:16:54,721 autoreload 3680 15972 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:16:56,492 autoreload 4760 1472 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 12:16:59,285 autoreload 4760 1472 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:17:01,072 autoreload 2884 19236 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 12:17:01,192 connectionpool 2884 18228 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 12:17:01,786 connectionpool 2884 18228 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 12:17:05,831 autoreload 2884 19236 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:17:07,759 autoreload 8956 2064 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 12:17:11,572 connectionpool 8956 13100 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
django.request ERROR 2024-05-13 12:17:11,604 log 8956 13776 Internal Server Error: /s/
Traceback (most recent call last):
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 39, in sentry_patched_render
    return old_render(self)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DoesNotExist is not JSON serializable
urllib3.connectionpool DEBUG 2024-05-13 12:17:12,248 connectionpool 8956 13100 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 12:17:39,686 autoreload 8956 2064 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:17:41,460 autoreload 11576 13892 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 12:17:45,462 autoreload 11576 13892 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:17:47,496 autoreload 15112 19276 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 12:17:49,341 autoreload 15112 19276 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:17:51,350 autoreload 7468 13708 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 12:17:52,109 connectionpool 7468 9476 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
django.request ERROR 2024-05-13 12:17:52,133 log 7468 2744 Internal Server Error: /s/
Traceback (most recent call last):
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 39, in sentry_patched_render
    return old_render(self)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DoesNotExist is not JSON serializable
urllib3.connectionpool DEBUG 2024-05-13 12:17:52,809 connectionpool 7468 9476 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 12:18:20,868 autoreload 7468 13708 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:18:22,674 autoreload 14708 4184 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 12:18:59,684 autoreload 14708 4184 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:19:01,441 autoreload 16116 11240 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 12:19:06,374 autoreload 16116 11240 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:19:08,167 autoreload 14844 8080 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 12:19:41,201 autoreload 14844 8080 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:19:42,900 autoreload 15884 4308 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 12:20:05,870 autoreload 15884 4308 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:20:07,836 autoreload 14560 9048 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 12:20:07,964 connectionpool 14560 16740 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 12:20:08,524 connectionpool 14560 16740 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 12:20:11,574 autoreload 14560 9048 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:20:13,282 autoreload 4056 14052 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 12:20:21,339 autoreload 4056 14052 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:20:23,083 autoreload 17772 5484 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 12:20:27,956 autoreload 17772 5484 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:20:29,756 autoreload 7956 11244 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 12:20:29,876 connectionpool 7956 1900 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 12:20:30,467 connectionpool 7956 1900 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 12:20:42,094 autoreload 7956 11244 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:20:43,845 autoreload 8552 17220 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 12:20:58,662 autoreload 8552 17220 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:21:00,371 autoreload 9824 19216 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 12:21:05,246 autoreload 9824 19216 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:21:07,071 autoreload 2772 11684 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 12:21:08,774 autoreload 2772 11684 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:21:10,519 autoreload 3684 15120 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 12:21:29,243 autoreload 3684 15120 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:21:31,122 autoreload 1064 16688 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 12:21:31,263 connectionpool 1064 9036 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 12:21:31,825 connectionpool 1064 9036 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 12:21:36,957 autoreload 1064 16688 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:21:38,937 autoreload 16020 10624 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 12:21:39,058 connectionpool 16020 16468 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 12:21:39,641 connectionpool 16020 16468 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 12:21:40,631 autoreload 16020 10624 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:21:42,533 autoreload 16484 3176 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 12:21:46,441 autoreload 16484 3176 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:21:48,443 autoreload 18532 19332 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 12:21:52,460 autoreload 18532 19332 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:21:54,335 autoreload 12720 4692 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 12:21:54,447 connectionpool 12720 3900 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 12:21:55,012 connectionpool 12720 3900 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 12:21:56,994 autoreload 12720 4692 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:21:58,802 autoreload 14584 14108 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 12:21:58,939 connectionpool 14584 15340 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 12:21:59,566 connectionpool 14584 15340 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 12:22:02,603 autoreload 14584 14108 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:22:04,580 autoreload 14828 16592 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 12:22:04,724 connectionpool 14828 17048 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 12:22:05,398 connectionpool 14828 17048 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 12:22:07,298 autoreload 14828 16592 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:22:09,241 autoreload 852 4720 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 12:22:09,454 connectionpool 852 15816 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 12:22:10,083 connectionpool 852 15816 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 12:22:11,018 autoreload 852 4720 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:22:12,761 autoreload 16100 4632 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 12:22:12,921 connectionpool 16100 19128 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 12:22:13,595 connectionpool 16100 19128 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 12:22:22,892 autoreload 16100 4632 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:22:24,699 autoreload 5472 10448 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 12:22:24,827 connectionpool 5472 18272 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 12:22:25,404 connectionpool 5472 18272 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 12:22:27,342 autoreload 5472 10448 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:22:29,186 autoreload 10460 14556 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 12:22:33,117 autoreload 10460 14556 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:22:34,848 autoreload 9872 7052 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 12:22:52,523 autoreload 9872 7052 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:22:54,383 autoreload 19236 2884 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 12:24:08,518 autoreload 19236 2884 C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:24:10,402 autoreload 10676 15916 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 12:24:18,556 autoreload 10676 15916 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 12:24:20,567 autoreload 16196 18636 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 13:39:58,354 autoreload 16196 18636 C:\Users\DEV-018\Desktop\sakib\demo\demo\settings.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 13:39:59,264 autoreload 14268 16440 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 13:40:11,154 autoreload 14268 16440 C:\Users\DEV-018\Desktop\sakib\demo\demo\settings.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 13:40:11,958 autoreload 10536 9040 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 13:40:13,356 autoreload 10536 9040 C:\Users\DEV-018\Desktop\sakib\demo\demo\settings.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 13:40:14,157 autoreload 5396 16136 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 13:41:28,787 connectionpool 5396 16676 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
base.views WARNING 2024-05-13 13:41:28,840 views 5396 10324 Error in Get request in Snippet details .....GET Snippet matching query does not exist.
django.request ERROR 2024-05-13 13:41:28,867 log 5396 10324 Internal Server Error: /sd/18/
Traceback (most recent call last):
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 39, in sentry_patched_render
    return old_render(self)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DoesNotExist is not JSON serializable
urllib3.connectionpool DEBUG 2024-05-13 13:41:29,182 connectionpool 5396 16676 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-13 13:41:29,332 connectionpool 5396 16676 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-13 13:41:29,797 connectionpool 5396 16676 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-13 13:41:29,958 connectionpool 5396 16676 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 14:03:18,107 autoreload 5396 16136 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 14:03:18,962 autoreload 4984 7148 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 14:03:19,035 connectionpool 4984 6804 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 14:03:19,442 connectionpool 4984 6804 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 14:03:20,268 autoreload 4984 7148 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 14:03:21,054 autoreload 988 11536 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 14:03:21,126 connectionpool 988 12720 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 14:03:21,499 connectionpool 988 12720 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 14:03:26,504 autoreload 988 11536 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 14:03:27,291 autoreload 15428 18816 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 14:03:27,362 connectionpool 15428 14448 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 14:03:27,733 connectionpool 15428 14448 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 14:03:29,634 autoreload 15428 18816 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 14:03:30,478 autoreload 17456 15924 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 14:03:31,896 autoreload 17456 15924 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 14:03:32,708 autoreload 18036 5892 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 14:03:37,229 autoreload 18036 5892 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 14:03:38,072 autoreload 16924 4360 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 14:03:39,514 autoreload 16924 4360 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 14:03:40,297 autoreload 16156 1472 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 14:03:47,511 connectionpool 16156 9516 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
base.views WARNING 2024-05-13 14:03:47,553 views 16156 16052 Error in Get request in Snippet details .....GET Snippet matching query does not exist.
django.request ERROR 2024-05-13 14:03:47,577 log 16156 16052 Internal Server Error: /sd/18/
Traceback (most recent call last):
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 39, in sentry_patched_render
    return old_render(self)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DoesNotExist is not JSON serializable
urllib3.connectionpool DEBUG 2024-05-13 14:03:47,912 connectionpool 16156 9516 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-13 14:03:48,076 connectionpool 16156 9516 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-13 14:03:48,256 connectionpool 16156 9516 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-13 14:03:48,417 connectionpool 16156 9516 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 14:06:49,993 autoreload 16156 1472 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 14:06:50,766 autoreload 19164 19016 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 14:06:50,836 connectionpool 19164 11280 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 14:06:51,215 connectionpool 19164 11280 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 14:06:55,160 autoreload 19164 19016 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 14:06:55,930 autoreload 5428 17604 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 14:06:56,019 connectionpool 5428 5116 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 14:06:56,376 connectionpool 5428 5116 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 14:06:57,241 autoreload 5428 17604 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 14:06:58,010 autoreload 7824 4612 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 14:07:05,706 autoreload 7824 4612 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 14:07:06,472 autoreload 5288 5408 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 14:59:27,999 autoreload 5288 5408 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 14:59:28,799 autoreload 18908 17936 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-13 16:58:38,778 autoreload 18908 17936 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 16:58:40,602 autoreload 15788 2516 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-13 16:58:40,734 connectionpool 15788 19372 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-13 16:58:41,320 connectionpool 15788 19372 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-13 16:59:03,370 autoreload 15788 2516 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-13 16:59:05,370 autoreload 20068 6416 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-14 10:19:45,175 autoreload 20340 20100 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-14 10:20:31,557 connectionpool 20340 10740 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
base.views INFO 2024-05-14 10:20:31,569 views 20340 18060 Get request for a particular data 
urllib3.connectionpool DEBUG 2024-05-14 10:20:32,371 connectionpool 20340 10740 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 10:20:32,624 connectionpool 20340 10740 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 10:22:15,166 connectionpool 20340 10740 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 10:23:12,953 connectionpool 20340 10740 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-14 10:23:48,996 autoreload 17428 17248 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-14 10:24:17,337 connectionpool 17428 6460 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-14 10:24:17,912 connectionpool 17428 6460 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-14 10:46:39,528 autoreload 1500 15320 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-14 10:46:39,619 connectionpool 1500 16596 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-14 10:46:40,294 connectionpool 1500 16596 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-14 10:49:15,968 autoreload 1500 15320 C:\Users\DEV-018\Desktop\sakib\demo\demo\settings.py changed, reloading.
django.utils.autoreload INFO 2024-05-14 10:49:17,051 autoreload 1064 18020 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-14 10:49:17,138 connectionpool 1064 11168 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-14 10:49:17,667 connectionpool 1064 11168 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-14 10:49:23,927 autoreload 2728 5300 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-14 10:49:24,021 connectionpool 2728 10540 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-14 10:49:24,547 connectionpool 2728 10540 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-14 10:50:56,427 autoreload 4244 15612 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-14 10:51:00,078 connectionpool 4244 19296 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
django.request WARNING 2024-05-14 10:51:00,275 log 4244 9660 Not Found: /favicon.ico
urllib3.connectionpool DEBUG 2024-05-14 10:51:00,701 connectionpool 4244 19296 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 10:51:00,906 connectionpool 4244 19296 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 10:51:01,111 connectionpool 4244 19296 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 10:51:01,316 connectionpool 4244 19296 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 10:51:01,522 connectionpool 4244 19296 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 10:51:01,726 connectionpool 4244 19296 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 10:51:01,920 connectionpool 4244 19296 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 10:51:02,073 connectionpool 4244 19296 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 10:51:02,237 connectionpool 4244 19296 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 10:51:02,441 connectionpool 4244 19296 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 10:51:02,646 connectionpool 4244 19296 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 10:51:02,851 connectionpool 4244 19296 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 10:51:03,043 connectionpool 4244 19296 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 10:51:03,230 connectionpool 4244 19296 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 10:51:16,776 connectionpool 4244 19296 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 10:51:16,980 connectionpool 4244 19296 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 10:51:17,186 connectionpool 4244 19296 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 10:51:17,338 connectionpool 4244 19296 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 10:51:17,493 connectionpool 4244 19296 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 10:51:17,700 connectionpool 4244 19296 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 10:51:17,905 connectionpool 4244 19296 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 10:51:18,109 connectionpool 4244 19296 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 10:51:18,315 connectionpool 4244 19296 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 10:51:18,469 connectionpool 4244 19296 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 10:52:50,575 connectionpool 4244 19296 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 10:53:26,621 connectionpool 4244 19296 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 10:53:46,282 connectionpool 4244 19296 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 10:55:33,318 connectionpool 4244 19296 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
base.views INFO 2024-05-14 10:55:55,926 views 4244 19268 Get request for a particular data 
urllib3.connectionpool DEBUG 2024-05-14 10:55:56,128 connectionpool 4244 19296 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 10:56:17,017 connectionpool 4244 19296 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.request ERROR 2024-05-14 10:58:57,922 log 4244 19268 Internal Server Error: /r/
Traceback (most recent call last):
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\Desktop\sakib\demo\base\views.py", line 92, in post
    if r_data.is_valid():
       ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\serializers.py", line 442, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV-018\Desktop\sakib\demo\base\serlizers.py", line 102, in to_internal_value
    resource_data = data['resource']
                    ~~~~^^^^^^^^^^^^
KeyError: 'resource'
urllib3.connectionpool DEBUG 2024-05-14 10:58:58,095 connectionpool 4244 19296 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 10:58:58,297 connectionpool 4244 19296 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:03:25,361 connectionpool 4244 19296 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-14 11:09:16,626 autoreload 4244 15612 C:\Users\DEV-018\Desktop\sakib\demo\demo\urls.py changed, reloading.
django.utils.autoreload INFO 2024-05-14 11:09:18,675 autoreload 3880 8236 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-14 11:09:58,024 connectionpool 3880 7520 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-14 11:09:58,580 connectionpool 3880 7520 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-14 11:13:47,666 autoreload 3880 8236 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-14 11:13:49,676 autoreload 11092 14172 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-14 11:13:50,173 connectionpool 11092 18652 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-14 11:13:50,702 connectionpool 11092 18652 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-14 11:14:17,420 autoreload 11092 14172 C:\Users\DEV-018\Desktop\sakib\demo\base\views.py changed, reloading.
django.utils.autoreload INFO 2024-05-14 11:14:19,644 autoreload 7304 12256 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-14 11:14:22,362 connectionpool 7304 12856 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
django.request WARNING 2024-05-14 11:14:23,147 log 7304 14936 Not Found: /favicon.ico
urllib3.connectionpool DEBUG 2024-05-14 11:14:23,798 connectionpool 7304 12856 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:14:24,004 connectionpool 7304 12856 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:14:24,207 connectionpool 7304 12856 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:14:24,412 connectionpool 7304 12856 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:14:24,616 connectionpool 7304 12856 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:14:24,820 connectionpool 7304 12856 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:14:25,028 connectionpool 7304 12856 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:14:25,231 connectionpool 7304 12856 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:14:25,436 connectionpool 7304 12856 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:14:25,641 connectionpool 7304 12856 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:14:25,846 connectionpool 7304 12856 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:14:26,051 connectionpool 7304 12856 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:14:26,256 connectionpool 7304 12856 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:14:26,458 connectionpool 7304 12856 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:14:26,664 connectionpool 7304 12856 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:14:33,616 connectionpool 7304 12856 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:14:33,834 connectionpool 7304 12856 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:14:34,036 connectionpool 7304 12856 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:14:34,243 connectionpool 7304 12856 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:14:34,448 connectionpool 7304 12856 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:14:34,652 connectionpool 7304 12856 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:14:34,857 connectionpool 7304 12856 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:14:35,061 connectionpool 7304 12856 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:14:35,216 connectionpool 7304 12856 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:14:35,376 connectionpool 7304 12856 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:15:29,539 connectionpool 7304 12856 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:15:31,792 connectionpool 7304 12856 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:15:51,149 connectionpool 7304 12856 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-14 11:17:04,314 autoreload 18012 9424 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-14 11:18:02,276 autoreload 12220 7652 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-05-14 11:20:47,134 autoreload 16320 18084 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-14 11:20:48,855 connectionpool 16320 11092 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-14 11:20:49,568 connectionpool 16320 11092 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:20:49,714 connectionpool 16320 11092 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:20:49,953 connectionpool 16320 11092 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:20:50,155 connectionpool 16320 11092 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:20:50,360 connectionpool 16320 11092 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:20:50,565 connectionpool 16320 11092 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:20:50,771 connectionpool 16320 11092 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:21:57,740 connectionpool 16320 11092 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:21:57,948 connectionpool 16320 11092 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-14 11:21:58,125 autoreload 16320 18084 C:\Users\DEV-018\Desktop\sakib\demo\demo\urls.py changed, reloading.
django.utils.autoreload INFO 2024-05-14 11:21:59,893 autoreload 11064 7312 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-05-14 11:22:09,779 connectionpool 11064 4924 Starting new HTTPS connection (1): o4507225874235392.ingest.us.sentry.io:443
urllib3.connectionpool DEBUG 2024-05-14 11:22:10,439 connectionpool 11064 4924 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:22:10,645 connectionpool 11064 4924 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:22:10,851 connectionpool 11064 4924 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:22:11,053 connectionpool 11064 4924 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:22:11,259 connectionpool 11064 4924 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:22:11,468 connectionpool 11064 4924 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
urllib3.connectionpool DEBUG 2024-05-14 11:22:11,667 connectionpool 11064 4924 https://o4507225874235392.ingest.us.sentry.io:443 "POST /api/4507226192740352/envelope/ HTTP/1.1" 200 0
django.utils.autoreload INFO 2024-05-14 11:23:37,380 autoreload 11064 7312 C:\Users\DEV-018\Desktop\sakib\demo\demo\urls.py changed, reloading.
django.utils.autoreload INFO 2024-05-14 11:23:40,252 autoreload 1268 6896 Watching for file changes with StatReloader
